version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/socket-deploy
    overwrite: yes

permissions:
  - object: /home/ubuntu/socket-deploy
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
